version: "3.9"

volumes:
  users-db-volume:
  rabbitmq-volume:

services:
  users-db:
    image: postgres:latest
    container_name: users-db
    environment:
      POSTGRES_DB: "users-db"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 0908yutfdftgyhuji3og
      PGDATA: /var/lib/postgresql/data
    volumes:
      - users-db-volume:/var/lib/postgresql/data
    ports:
      - "5543:5432"
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
  
  user-registration-service:
    build:
      context: ./src/UserRegistrationService
      dockerfile: Dockerfile
    container_name: user-registration-service
    ports:
      - "5010:80"
    environment:
      "ConnectionStrings__RabbitMQ": "amqps://rabbit:rabbitmq@rabbitmq:5672/"
    depends_on:
      - rabbitmq
  
  user-storage-service:
    build:
      context: ./src/UserStorageService
      dockerfile: Dockerfile
    container_name: user-storage-service
    ports:
      - "5011:80"
    environment:
      "ConnectionStrings__UsersDb": "Server=host.docker.internal;Port=5543;Database=users-db;User Id=user;Password=0908yutfdftgyhuji3og;"
      "ConnectionStrings__RabbitMQ": "amqps://rabbit:rabbitmq@host.docker.internal:5672/"
    depends_on:
      - rabbitmq
      - users-db
      - user-registration-service
  